import './globals.css'

import Navbar from '@/components/Navbar'
import Footer from '@/components/Footer'

import { montserrat } from '@/components/fonts'

export const metadata = {
  title: {
    template: '%s | Herbshop',
    default: 'Herbshop', // a default is required when creating a template
  },
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang='en'>
      <body className={montserrat.className}>
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  )
}
