import './globals.css'
import { Inter } from 'next/font/google'
import { Montserrat } from 'next/font/google'

import Navbar from '@/components/Navbar'
import Footer from '@/components/Footer'

const montserrat = Montserrat({ subsets: ['latin'] })

export const metadata = {
  title: {
    template: '%s | Herbshop',
    default: 'Herbshop', // a default is required when creating a template
  },
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang='en'>
      <body className={montserrat.className}>
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  )
}
