export { default as Facebook } from './Facebook'
export { default as Instagram } from './Instagram'
export { default as Twitter } from './Twitter'
export { default as Linkin } from './Linkin'
export { default as PlantsPot } from './PlantsPot'
export { default as Fashion } from './Fashion'
export { default as Handmade } from './Handmade'
